# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pnc < Formula
  desc "Paranoco CLI toolbelt"
  homepage "https://github.com/paranoco/pnc"
  version "0.0.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/paranoco/pnc/releases/download/v0.0.1/pnc_0.0.1_darwin_amd64.tar.gz"
    sha256 "900481ebdb0209bf82a1204b285ef5e8abb7e1f75beda5c3bb7bcf67cf1edade"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/paranoco/pnc/releases/download/v0.0.1/pnc_0.0.1_darwin_arm64.tar.gz"
    sha256 "1ee2dafe0e7d921bd2fa21f7ded20dce3c7a5318b8098248df2191d334aec523"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/paranoco/pnc/releases/download/v0.0.1/pnc_0.0.1_linux_amd64.tar.gz"
    sha256 "cb16b08d4551c8e93a29a740bf6b6a9aa067778a7ca9e436d5ff372b2efa7633"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/paranoco/pnc/releases/download/v0.0.1/pnc_0.0.1_linux_armv6.tar.gz"
    sha256 "e4d916eb759cb119834abc40ceb33a4ee6c4759a981f3f71c43bd7011160b3a2"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/paranoco/pnc/releases/download/v0.0.1/pnc_0.0.1_linux_arm64.tar.gz"
    sha256 "40e35adab6fa65d6767b7b58515bc343499935e94c573e7086c2cfdf0803d2bc"
  end

  def install
    bin.install "pnc"
  end
end
