# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pnc < Formula
  desc "Paranoco CLI toolbelt"
  homepage "https://github.com/paranoco/pnc"
  version "0.1.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/paranoco/pnc/releases/download/v0.1.2/pnc_0.1.2_darwin_amd64.tar.gz"
    sha256 "d3d9cc8076c667fab81edd85fb1ea56cd0473ed12eebfc6309014b273851c40b"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/paranoco/pnc/releases/download/v0.1.2/pnc_0.1.2_darwin_arm64.tar.gz"
    sha256 "fc3b730a7ef045ffd5ea2c0e53224b136953fa070daa7f85590b0ae267bce882"
  end

  def install
    bin.install "pnc"
  end
end
